### ISSUE TITLE
pisitools.dosed çalışmıyor mu? 

### ISSUE THREAD

**Issue by ertugerata** [safaariman/pisi#1]
```
Sandbox enabled build...
Traceback (most recent call last):
  File "/git/BuildFiles/system/base/openssl/actions.py", line 13, in setup
    pisitools.dosed("Configure", " $prefix/$libdir/engines ", " /%{_lib}/engines ")
  File "/usr/lib/python3.6/site-packages/pisi/actionsapi/pisitools.py", line 208, in dosed
    for line in fileinput.input(sourceFile, inplace = 1, backup = backupExtension):
  File "/usr/lib/python3.6/fileinput.py", line 250, in __next__
    line = self._readline()
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa9 in position 3102: invalid start byte
```

**Comment by ertugerata** [comment]
bunu kapatıyorum başka yerlerde dosed in çalıştığını gözlemledim. tekrarlarsak açarız.
